ALTER TABLE app_user RENAME TO resident;

CREATE TABLE household_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL REFERENCES house(id) ON DELETE CASCADE,
    resident_id BIGINT NOT NULL REFERENCES resident(id) ON DELETE CASCADE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    moved_in_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    moved_out_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_household_membership_house_resident UNIQUE (house_id, resident_id)
);

CREATE INDEX idx_household_membership_house ON household_membership(house_id);
CREATE INDEX idx_household_membership_resident ON household_membership(resident_id);

INSERT INTO household_membership (house_id, resident_id, active, moved_in_at, created_at, updated_at)
SELECT hr.house_id,
       r.id,
       TRUE,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM house_resident hr
JOIN resident r ON lower(r.email) = lower(hr.email)
ON CONFLICT (house_id, resident_id) DO NOTHING;

DROP TABLE house_resident;
