CREATE TABLE IF NOT EXISTS community_post_comment_reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL REFERENCES community_post_comment(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES resident(id) ON DELETE CASCADE,
    reaction_type VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_comment_reaction_comment_user UNIQUE (comment_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_comment_reaction_comment
    ON community_post_comment_reaction(comment_id);

CREATE INDEX IF NOT EXISTS idx_comment_reaction_comment_type
    ON community_post_comment_reaction(comment_id, reaction_type);
