CREATE TABLE house_resident (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL REFERENCES house(id) ON DELETE CASCADE,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(320) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_house_resident_house_id ON house_resident(house_id);
CREATE UNIQUE INDEX uq_house_resident_house_email ON house_resident(house_id, lower(email));

INSERT INTO house_resident (house_id, full_name, email, created_at, updated_at)
SELECT id, resident_name, resident_email, COALESCE(claimed_at, created_at), CURRENT_TIMESTAMP
FROM house
WHERE resident_name IS NOT NULL
  AND resident_email IS NOT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE house DROP COLUMN resident_name;
ALTER TABLE house DROP COLUMN resident_email;
