UPDATE house
SET status = 'NOT_OCCUPIED'
WHERE status = 'PENDING';

UPDATE house
SET status = 'OCCUPIED'
WHERE status = 'COMPLETED';

UPDATE house
SET status = 'UNKNOWN'
WHERE status IS NULL OR status = '';

ALTER TABLE house
DROP CONSTRAINT IF EXISTS ck_house_status;

ALTER TABLE house
ADD CONSTRAINT ck_house_status CHECK (status IN ('UNKNOWN', 'NOT_OCCUPIED', 'OCCUPIED'));

CREATE TABLE onboarding_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token VARCHAR(64) NOT NULL UNIQUE,
    house_id BIGINT NOT NULL REFERENCES house(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL,
    contact_type VARCHAR(10),
    contact_value VARCHAR(320),
    verification_token VARCHAR(64) UNIQUE,
    verification_expires_at TIMESTAMPTZ,
    verified_at TIMESTAMPTZ,
    auth_provider VARCHAR(30),
    auth_subject VARCHAR(255),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_onboarding_session_house_id ON onboarding_session(house_id);
CREATE INDEX idx_onboarding_session_status ON onboarding_session(status);
