CREATE TABLE community_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    body_text VARCHAR(4000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_community_post_created ON community_post(created_at DESC, id DESC);

CREATE TABLE community_post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES community_post(id) ON DELETE CASCADE,
    media_type VARCHAR(20) NOT NULL,
    media_url VARCHAR(1000) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_community_post_media_post ON community_post_media(post_id, sort_order, id);
