CREATE TABLE community_post_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES community_post(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_community_post_like_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX idx_community_post_like_post ON community_post_like(post_id);

CREATE TABLE community_post_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES community_post(id) ON DELETE CASCADE,
    author_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    body_text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_community_post_comment_post ON community_post_comment(post_id, created_at, id);
